#include "WorldManager.hpp"

#include <chrono>
#include <iostream>

#include "common/Util/perlinNoise.hpp"

WorldManager::WorldManager(ThreadSafeQueue<ChunkRequest>& requestQueue,
                           ThreadSafeQueue<GenerationTask>& meshingQueue,
                           ThreadSafeQueue<MeshingComplete>& completionQueue)
    : _requestQueue(requestQueue), _meshingQueue(meshingQueue), _completionQueue(completionQueue) {}

WorldManager::~WorldManager() {
    stop();
}

void WorldManager::start() {
    if (_running.load()) {
        std::cerr << "[WorldManager] Already running!\n";
        return;
    }

    _running.store(true);
    _generationWorkers.reserve(NUM_GENERATION_WORKERS);

    // Start generation workers
    for (int i = 0; i < NUM_GENERATION_WORKERS; ++i) {
        _generationWorkers.push_back(
            std::make_unique<std::thread>(&WorldManager::generationWorkerLoop, this));
    }

    // Start completion processor
    _completionProcessor =
        std::make_unique<std::thread>(&WorldManager::completionProcessorLoop, this);

    std::cout << "[WorldManager] Started " << NUM_GENERATION_WORKERS
              << " generation workers + 1 completion processor\n";
}

void WorldManager::stop() {
    if (!_running.load()) {
        return;
    }

    std::cout << "[WorldManager] Stopping all threads...\n";
    _running.store(false);
    _requestQueue.shutdown();    // Wake up generation workers
    _completionQueue.shutdown(); // Wake up completion processor

    // Join generation workers
    for (auto& worker : _generationWorkers) {
        if (worker && worker->joinable()) {
            worker->join();
        }
    }
    _generationWorkers.clear();

    // Join completion processor
    if (_completionProcessor && _completionProcessor->joinable()) {
        _completionProcessor->join();
    }

    std::cout << "[WorldManager] All threads stopped\n";
    std::cout << "[WorldManager] Stats - Chunks generated: " << _totalChunksGenerated.load()
              << ", Meshing tasks enqueued: " << _totalMeshingTasksEnqueued.load() << "\n";
}

void WorldManager::generationWorkerLoop() {
    ChunkRequest request;

    while (_running.load()) {
        // Block until a chunk request arrives
        if (!_requestQueue.wait_and_pop(request)) {
            // Queue shutdown signal received
            break;
        }

        const glm::ivec3& pos = request.chunkPosition;

        // Check if chunk is already loaded or being generated (with lock)
        {
            std::lock_guard<std::mutex> lock(_chunkMutex);

            // Skip if already loaded
            if (_loadedChunks.find(pos) != _loadedChunks.end()) {
                continue;
            }

            // Skip if already being generated by another worker
            if (_generatingChunks.find(pos) != _generatingChunks.end()) {
                continue;
            }

            // Mark as being generated
            _generatingChunks.insert(pos);
        }

        // Generate the chunk (this is the expensive part - do it outside the lock)
        auto startTime = std::chrono::high_resolution_clock::now();
        std::shared_ptr<Chunk> mainChunk = generateChunk(pos);
        auto endTime = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);

        // Log slow generation (>5ms)
        if (duration.count() > 5000) {
            std::cout << "[WorldManager] Chunk generation at (" << pos.x << ", " << pos.y << ", "
                      << pos.z << ") took " << duration.count() / 1000.0F << "ms\n";
        }

        // Store the chunk and update tracking (with lock)
        {
            std::lock_guard<std::mutex> lock(_chunkMutex);
            _loadedChunks[pos] = mainChunk;
            _generatingChunks.erase(pos);
            _totalChunksGenerated.fetch_add(1);
        }

        // Mesh the newly generated chunk
        if (enqueueMeshingTask(pos)) {
            // Mark neighbors as dirty for re-meshing
            markNeighborsDirty(pos);
        }
    }
}

std::shared_ptr<Chunk> WorldManager::generateChunk(const glm::ivec3& pos) {
    auto chunk = std::make_shared<Chunk>(pos.x, pos.y, pos.z);

    // Simple terrain generation using Perlin noise
    constexpr float scale = 0.05F; // Noise scale
    constexpr int groundLevel = 64;

    for (int x = 0; x < Chunk::CHUNK_SIZE; ++x) {
        for (int z = 0; z < Chunk::CHUNK_SIZE; ++z) {
            // World coordinates
            int worldX = pos.x * Chunk::CHUNK_SIZE + x;
            int worldZ = pos.z * Chunk::CHUNK_SIZE + z;

            // Generate height using Perlin noise
            // float noise =
            //     perlinNoiseByCoordinates(static_cast<float>(worldX) * scale,
            //                              static_cast<float>(worldZ) * scale, scale, 12345, 4,
            //                              0.5F);
            // int height = groundLevel + static_cast<int>(noise * 20.0F); // ±20 blocks variation
            int height = groundLevel + 16;

            for (int y = 0; y < Chunk::CHUNK_SIZE; ++y) {
                int worldY = pos.y * Chunk::CHUNK_SIZE + y;

                if (worldY <= height) {
                    // Place blocks below height
                    chunk->setBlock(x, y, z, 1); // Grass (block ID 1)
                } else {
                    chunk->setBlock(x, y, z, Chunk::AIR_BLOCK_ID); // Air
                }
            }
        }
    }

    return chunk;
}

std::shared_ptr<Chunk> WorldManager::getChunkFromCache(const glm::ivec3& pos) {
    // Caller must hold _chunkMutex lock
    auto it = _loadedChunks.find(pos);
    if (it != _loadedChunks.end()) {
        return it->second;
    }
    return nullptr;
}

void WorldManager::markNeighborsDirty(const glm::ivec3& pos) {
    static constexpr glm::ivec3 neighborOffsets[] = {{1, 0, 0},  {-1, 0, 0}, {0, 1, 0},
                                                     {0, -1, 0}, {0, 0, 1},  {0, 0, -1}};

    std::lock_guard<std::mutex> lock(_chunkMutex);

    for (const glm::ivec3& offset : neighborOffsets) {
        const glm::ivec3 neighborPos = pos + offset;

        // Only mark dirty if chunk is loaded
        if (_loadedChunks.find(neighborPos) != _loadedChunks.end()) {
            _dirtyChunks.insert(neighborPos);

            // If not currently being meshed, enqueue it
            if (_meshingChunks.find(neighborPos) == _meshingChunks.end()) {
                _meshingChunks.insert(neighborPos);

                GenerationTask task(neighborPos, _loadedChunks[neighborPos]);
                task.neighborNorth =
                    getChunkFromCache(glm::ivec3(neighborPos.x, neighborPos.y, neighborPos.z + 1));
                task.neighborSouth =
                    getChunkFromCache(glm::ivec3(neighborPos.x, neighborPos.y, neighborPos.z - 1));
                task.neighborEast =
                    getChunkFromCache(glm::ivec3(neighborPos.x + 1, neighborPos.y, neighborPos.z));
                task.neighborWest =
                    getChunkFromCache(glm::ivec3(neighborPos.x - 1, neighborPos.y, neighborPos.z));
                task.neighborTop =
                    getChunkFromCache(glm::ivec3(neighborPos.x, neighborPos.y + 1, neighborPos.z));
                task.neighborBottom =
                    getChunkFromCache(glm::ivec3(neighborPos.x, neighborPos.y - 1, neighborPos.z));

                _meshingQueue.push(std::move(task));
                _totalMeshingTasksEnqueued.fetch_add(1);
            }
        }
    }
}

WorldManager::QueueStats WorldManager::getQueueStats() const {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    return QueueStats{_requestQueue.size(), _meshingQueue.size(), _loadedChunks.size(),
                      _generatingChunks.size(), _meshingChunks.size()};
}

void WorldManager::completionProcessorLoop() {
    MeshingComplete completion;

    while (_running.load()) {
        // Block until a completion notification arrives
        if (!_completionQueue.wait_and_pop(completion)) {
            // Queue shutdown signal received
            break;
        }

        const glm::ivec3& pos = completion.chunkPosition;

        std::lock_guard<std::mutex> lock(_chunkMutex);

        // Remove from meshing set
        _meshingChunks.erase(pos);

        // Check if chunk is dirty (needs re-meshing)
        if (_dirtyChunks.find(pos) != _dirtyChunks.end()) {
            _dirtyChunks.erase(pos);

            // Re-mesh with updated neighbors
            if (_loadedChunks.find(pos) != _loadedChunks.end() &&
                _meshingChunks.find(pos) == _meshingChunks.end()) {

                _meshingChunks.insert(pos);

                GenerationTask task(pos, _loadedChunks[pos]);
                task.neighborNorth = getChunkFromCache(glm::ivec3(pos.x, pos.y, pos.z + 1));
                task.neighborSouth = getChunkFromCache(glm::ivec3(pos.x, pos.y, pos.z - 1));
                task.neighborEast = getChunkFromCache(glm::ivec3(pos.x + 1, pos.y, pos.z));
                task.neighborWest = getChunkFromCache(glm::ivec3(pos.x - 1, pos.y, pos.z));
                task.neighborTop = getChunkFromCache(glm::ivec3(pos.x, pos.y + 1, pos.z));
                task.neighborBottom = getChunkFromCache(glm::ivec3(pos.x, pos.y - 1, pos.z));

                _meshingQueue.push(std::move(task));
                _totalMeshingTasksEnqueued.fetch_add(1);
            }
        }
    }
}

bool WorldManager::enqueueMeshingTask(const glm::ivec3& pos) {
    std::lock_guard<std::mutex> lock(_chunkMutex);

    auto chunkIt = _loadedChunks.find(pos);
    if (chunkIt == _loadedChunks.end()) {
        return false;
    }

    // Skip if already being meshed (deduplication)
    if (_meshingChunks.find(pos) != _meshingChunks.end()) {
        // Mark as dirty so it gets re-meshed after current mesh completes
        _dirtyChunks.insert(pos);
        return false;
    }

    // Mark as being meshed
    _meshingChunks.insert(pos);

    GenerationTask task(pos, chunkIt->second);
    task.neighborNorth = getChunkFromCache(glm::ivec3(pos.x, pos.y, pos.z + 1));
    task.neighborSouth = getChunkFromCache(glm::ivec3(pos.x, pos.y, pos.z - 1));
    task.neighborEast = getChunkFromCache(glm::ivec3(pos.x + 1, pos.y, pos.z));
    task.neighborWest = getChunkFromCache(glm::ivec3(pos.x - 1, pos.y, pos.z));
    task.neighborTop = getChunkFromCache(glm::ivec3(pos.x, pos.y + 1, pos.z));
    task.neighborBottom = getChunkFromCache(glm::ivec3(pos.x, pos.y - 1, pos.z));

    _meshingQueue.push(std::move(task));
    _totalMeshingTasksEnqueued.fetch_add(1);
    return true;
}
