#include "WorldManager.hpp"

#include <chrono>
#include <iostream>

#include <tracy/Tracy.hpp>

#include "common/Util/Util.hpp"

#ifndef CHUNK_TO_WORLD
#define CHUNK_TO_WORLD(b, c) ((c) * Chunk::CHUNK_SIZE + (b))
#endif
WorldManager::WorldManager(ThreadSafeQueue<ChunkRequest>& requestQueue,
                           ThreadSafeQueue<GenerationTask>& meshingQueue,
                           ThreadSafeQueue<MeshingComplete>& completionQueue)
    : _requestQueue(requestQueue), _meshingQueue(meshingQueue), _completionQueue(completionQueue) {
    std::vector<double> x;
    std::vector<double> y;
    // x = {-1.0, -0.8, -0.5, -0.3, 0.1, 0.3, 0.5, 0.7, 0.8, 0.9, 1.0};
    // // y = {20, 31, 45, 60, 70, 80, 119, 137, 148, 200, 255};
    // x = {-1.0, -0.8, -0.5, -0.3, 0.0, 0.1, 0.5, 0.7, 0.75, 0.8, 1.0, 1.2};
    // y = {20, 31, 35, 40, 50, 65, 69, 90, 100, 150, 200, 255};
    x = {-1.0, -0.8, -0.5, -0.3, 0.0, 0.5, 0.7, 0.75, 0.8, 1.0, 1.2};
    y = {20, 31, 35, 40, 50, 69, 90, 100, 130, 220, 255};
    _heightSpline.set_points(x, y, tk::spline::cspline);
}

WorldManager::~WorldManager() {
    stop();
}

void WorldManager::start() {
    if (_running.load()) {
        std::cerr << "[WorldManager] Already running!\n";
        return;
    }

    _running.store(true);
    _generationWorkers.reserve(kNUM_GENERATION_WORKERS);

    // Start generation workers
    for (int i = 0; i < kNUM_GENERATION_WORKERS; ++i) {
        _generationWorkers.push_back(
            std::make_unique<std::thread>(&WorldManager::generationWorkerLoop, this));
    }

    _completionProcessor =
        std::make_unique<std::thread>(&WorldManager::completionProcessorLoop, this);

    std::cout << "[WorldManager] Started " << kNUM_GENERATION_WORKERS
              << " generation workers + 1 completion processor\n";
}

void WorldManager::stop() {
    if (!_running.load()) {
        return;
    }

    std::cout << "[WorldManager] Stopping all threads...\n";
    _running.store(false);
    _requestQueue.shutdown();    // Wake up generation workers
    _completionQueue.shutdown(); // Wake up completion processor

    // Join generation workers
    for (auto& worker : _generationWorkers) {
        if (worker && worker->joinable()) {
            worker->join();
        }
    }
    _generationWorkers.clear();

    if (_completionProcessor && _completionProcessor->joinable()) {
        _completionProcessor->join();
    }

    std::cout << "[WorldManager] All threads stopped\n";
    std::cout << "[WorldManager] Stats - Chunks generated: " << _totalChunksGenerated.load()
              << ", Meshing tasks enqueued: " << _totalMeshingTasksEnqueued.load() << "\n";
}

void WorldManager::generationWorkerLoop() {
    ZoneScoped;
    ChunkRequest request{};

    while (_running.load()) {
        // Block until a chunk request arrives
        if (!_requestQueue.wait_and_pop(request)) {
            // Queue shutdown signal received
            break;
        }

        TracyMessageL("Processing chunk request");
        const glm::ivec3& pos = request.chunkPosition;

        // Check if chunk is already loaded or being generated (with lock)
        {
            std::lock_guard<std::mutex> lock(_chunkMutex);

            // Skip if already loaded
            if (_loadedChunks.contains(pos)) {
                continue;
            }

            // Skip if already being generated by another worker
            if (_generatingChunks.contains(pos)) {
                continue;
            }

            // Mark as being generated
            _generatingChunks.insert(pos);
        }

        // Generate the chunk (this is the expensive part - do it outside the lock)
        auto startTime = std::chrono::high_resolution_clock::now();
        std::shared_ptr<Chunk> mainChunk = generateChunk(pos);
        auto endTime = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);

        // // Log slow generation (>5ms)
        // if (duration.count() > 5000) {
        //     std::cout << "[WorldManager] Chunk generation at (" << pos[0] << ", " << pos[1] << ", "
        //               << pos[2] << ") took " << duration.count() / 1000.0F << "ms\n";
        // }

        {
            std::lock_guard<std::mutex> lock(_chunkMutex);
            _loadedChunks[pos] = mainChunk;
            _generatingChunks.erase(pos);
            _totalChunksGenerated.fetch_add(1);
        }

        // Mesh the newly generated chunk
        if (enqueueMeshingTask(pos)) {
            // Mark neighbors as dirty for re-meshing
            markNeighborsDirty(pos);
        }
    }
}

std::shared_ptr<Chunk> WorldManager::getChunkFromCache(const glm::ivec3& pos) {
    // Caller must hold _chunkMutex lock
    auto it = _loadedChunks.find(pos);
    if (it != _loadedChunks.end()) {
        return it->second;
    }
    return nullptr;
}

void WorldManager::markNeighborsDirty(const glm::ivec3& pos) {
    static constexpr glm::ivec3 kNEIGHBOR_OFFSETS[] = {{1, 0, 0},  {-1, 0, 0}, {0, 1, 0},
                                                       {0, -1, 0}, {0, 0, 1},  {0, 0, -1}};

    std::lock_guard<std::mutex> lock(_chunkMutex);

    for (const glm::ivec3& offset : kNEIGHBOR_OFFSETS) {
        const glm::ivec3 kNEIGHBOR_POS = pos + offset;

        // Only mark dirty if chunk is loaded
        if (_loadedChunks.contains(kNEIGHBOR_POS)) {
            // bool wasAlreadyDirty = _dirtyChunks.find(kNEIGHBOR_POS) != _dirtyChunks.end();
            _dirtyChunks.insert(kNEIGHBOR_POS);

            // This prevents cascading re-meshes where chunks get meshed 5-7 times
            // Count how many neighbors exist (loaded) vs how many are possible
            int loadedNeighbors = 0;
            int possibleNeighbors = 0;
            for (const glm::ivec3& checkOffset : kNEIGHBOR_OFFSETS) {
                const glm::ivec3 kCHECK_POS = kNEIGHBOR_POS + checkOffset;

                // Count this as a possible neighbor if it's within world bounds
                // (Y >= 0 for bottom boundary check - no chunks below Y=0)
                if (kCHECK_POS[1] >= 0) {
                    possibleNeighbors++;
                    if (_loadedChunks.contains(kCHECK_POS)) {
                        loadedNeighbors++;
                    }
                }
            }

            // Re-mesh ONLY if chunk has ALL POSSIBLE neighbors loaded
            // This handles edge cases like Y=0 chunks that can't have a bottom neighbor
            if (loadedNeighbors == possibleNeighbors && !_meshingChunks.contains(kNEIGHBOR_POS)) {
                // Remove from dirty set since we're about to mesh it
                _dirtyChunks.erase(kNEIGHBOR_POS);
                _meshingChunks.insert(kNEIGHBOR_POS);

                GenerationTask task(kNEIGHBOR_POS, _loadedChunks[kNEIGHBOR_POS]);
                task.neighborNorth = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0], kNEIGHBOR_POS[1], kNEIGHBOR_POS[2] + 1));
                task.neighborSouth = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0], kNEIGHBOR_POS[1], kNEIGHBOR_POS[2] - 1));
                task.neighborEast = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0] + 1, kNEIGHBOR_POS[1], kNEIGHBOR_POS[2]));
                task.neighborWest = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0] - 1, kNEIGHBOR_POS[1], kNEIGHBOR_POS[2]));
                task.neighborTop = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0], kNEIGHBOR_POS[1] + 1, kNEIGHBOR_POS[2]));
                task.neighborBottom = getChunkFromCache(
                    glm::ivec3(kNEIGHBOR_POS[0], kNEIGHBOR_POS[1] - 1, kNEIGHBOR_POS[2]));

                _meshingQueue.push(std::move(task));
                _totalMeshingTasksEnqueued.fetch_add(1);
            }
        }
    }
}

WorldManager::QueueStats WorldManager::getQueueStats() const {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    return QueueStats{_requestQueue.size(),     _meshingQueue.size(),  _loadedChunks.size(),
                      _generatingChunks.size(), _meshingChunks.size(), _chunksToUnload.size()};
}

void WorldManager::completionProcessorLoop() {
    ZoneScoped;
    MeshingComplete completion{};

    while (_running.load()) {
        // Block until a completion notification arrives
        if (!_completionQueue.wait_and_pop(completion)) {
            // Queue shutdown signal received
            break;
        }

        const glm::ivec3& pos = completion.chunkPosition;

        std::lock_guard<std::mutex> lock(_chunkMutex);

        // Remove from meshing set
        _meshingChunks.erase(pos);

        // Check if chunk is dirty (needs re-meshing)
        if (_dirtyChunks.contains(pos)) {
            // Count how many neighbors are loaded vs possible
            static constexpr glm::ivec3 kNEIGHBOR_OFFSETS[] = {{1, 0, 0},  {-1, 0, 0}, {0, 1, 0},
                                                               {0, -1, 0}, {0, 0, 1},  {0, 0, -1}};
            int loadedNeighbors = 0;
            int possibleNeighbors = 0;
            for (const glm::ivec3& offset : kNEIGHBOR_OFFSETS) {
                const glm::ivec3 kCHECK_POS = pos + offset;

                // Count as possible if within world bounds (Y >= 0)
                if (kCHECK_POS[1] >= 0) {
                    possibleNeighbors++;
                    if (_loadedChunks.contains(kCHECK_POS)) {
                        loadedNeighbors++;
                    }
                }
            }

            // Only re-mesh if chunk has ALL POSSIBLE neighbors
            // Otherwise, keep it dirty and it will be picked up later
            if (loadedNeighbors == possibleNeighbors) {
                _dirtyChunks.erase(pos);

                // Re-mesh with updated neighbors
                if (_loadedChunks.contains(pos) && !_meshingChunks.contains(pos)) {

                    _meshingChunks.insert(pos);

                    GenerationTask task(pos, _loadedChunks[pos]);
                    task.neighborNorth = getChunkFromCache(glm::ivec3(pos[0], pos[1], pos[2] + 1));
                    task.neighborSouth = getChunkFromCache(glm::ivec3(pos[0], pos[1], pos[2] - 1));
                    task.neighborEast = getChunkFromCache(glm::ivec3(pos[0] + 1, pos[1], pos[2]));
                    task.neighborWest = getChunkFromCache(glm::ivec3(pos[0] - 1, pos[1], pos[2]));
                    task.neighborTop = getChunkFromCache(glm::ivec3(pos[0], pos[1] + 1, pos[2]));
                    task.neighborBottom = getChunkFromCache(glm::ivec3(pos[0], pos[1] - 1, pos[2]));

                    _meshingQueue.push(std::move(task));
                    _totalMeshingTasksEnqueued.fetch_add(1);
                }
            }
            // If not enough neighbors, keep it in _dirtyChunks to be retried later
        }
    }
}

bool WorldManager::enqueueMeshingTask(const glm::ivec3& pos) {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    return enqueueMeshingTaskInternal(pos);
}

bool WorldManager::enqueueMeshingTaskInternal(const glm::ivec3& pos) {
    // NOTE: This function assumes _chunkMutex is already locked by the caller!

    auto chunkIt = _loadedChunks.find(pos);
    if (chunkIt == _loadedChunks.end()) {
        return false;
    }

    // Skip if already being meshed (deduplication)
    if (_meshingChunks.contains(pos)) {
        // Mark as dirty so it gets re-meshed after current mesh completes
        _dirtyChunks.insert(pos);
        return false;
    }

    // Mark as being meshed
    _meshingChunks.insert(pos);

    GenerationTask task(pos, chunkIt->second);
    task.neighborNorth = getChunkFromCache(glm::ivec3(pos[0], pos[1], pos[2] + 1));
    task.neighborSouth = getChunkFromCache(glm::ivec3(pos[0], pos[1], pos[2] - 1));
    task.neighborEast = getChunkFromCache(glm::ivec3(pos[0] + 1, pos[1], pos[2]));
    task.neighborWest = getChunkFromCache(glm::ivec3(pos[0] - 1, pos[1], pos[2]));
    task.neighborTop = getChunkFromCache(glm::ivec3(pos[0], pos[1] + 1, pos[2]));
    task.neighborBottom = getChunkFromCache(glm::ivec3(pos[0], pos[1] - 1, pos[2]));

    _meshingQueue.push(std::move(task));
    _totalMeshingTasksEnqueued.fetch_add(1);
    return true;
}

void WorldManager::markChunkForUnload(const glm::ivec3& pos) {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    _chunksToUnload.insert(pos);
}

void WorldManager::unmarkChunkForUnload(const glm::ivec3& pos) {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    _chunksToUnload.erase(pos);
}

std::vector<glm::ivec3> WorldManager::unloadMarkedChunks() {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    std::vector<glm::ivec3> unloadedChunks;
    unloadedChunks.reserve(_chunksToUnload.size());

    for (const glm::ivec3& pos : _chunksToUnload) {
        // Remove from loaded chunks map (this frees RAM via shared_ptr)
        auto it = _loadedChunks.find(pos);
        if (it != _loadedChunks.end()) {
            _loadedChunks.erase(it);
            unloadedChunks.push_back(pos);
        }

        // Also remove from other tracking sets to keep state clean
        _generatingChunks.erase(pos);
        _meshingChunks.erase(pos);
        _dirtyChunks.erase(pos);
    }

    _chunksToUnload.clear();

    if (!unloadedChunks.empty()) {
        std::cout << "[WorldManager] Unloaded " << unloadedChunks.size() << " chunks from RAM\n";
    }

    return unloadedChunks;
}

std::vector<glm::ivec3> WorldManager::getLoadedChunkPositions() const {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    std::vector<glm::ivec3> positions;
    positions.reserve(_loadedChunks.size());

    for (const auto& [pos, chunk] : _loadedChunks) {
        positions.push_back(pos);
    }

    return positions;
}

bool WorldManager::isChunkLoaded(const glm::ivec3& pos) const {
    std::lock_guard<std::mutex> lock(_chunkMutex);
    return _loadedChunks.contains(pos);
}

void WorldManager::requestRemeshForAllChunks(const std::vector<glm::ivec3>& excludeChunks) {
    std::lock_guard<std::mutex> lock(_chunkMutex);

    // Convert exclude list to set for fast lookup
    std::unordered_set<glm::ivec3> excludeSet(excludeChunks.begin(), excludeChunks.end());

    int remeshedCount = 0;
    for (const auto& [pos, chunk] : _loadedChunks) {
        // Skip chunks that were unloaded
        if (excludeSet.contains(pos)) {
            continue;
        }

        // Mark as dirty and enqueue for meshing
        _dirtyChunks.insert(pos);

        // Use internal version to avoid deadlock (we already hold _chunkMutex)
        enqueueMeshingTaskInternal(pos);
        remeshedCount++;
    }

    std::cout << "[WorldManager] Requested re-meshing for " << remeshedCount << " loaded chunks\n";
}
