name: Generate doxygen documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Documentation generation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "Doxyfile"

      - name: Deploy documentation to 'doc' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

          publish_dir: ./doc/html

          publish_branch: doc

          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

          commit_message: "Deploy Doxygen documentation to doc branch"
          cname: "ft-minecraft.maem.lol"
