name: Generate doxygen documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
  runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Documentation generation
       uses: AgarwalSaurav/ghaction-doxygen-ghpages@release/v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          doxyfile-path: "Doxyfile" # Chemin vers votre Doxyfile
          html-output-folder: "doc/html"
          branch: "doc"