name: Generate doxygen documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Documentation generation
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: "Doxyfile"
